name: Hello World

on: 
  push:
    branches:
      - prod

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hello Worlld
        run: echo " Hello From GitHubActions!"
      
